[package]
name = "bearr-buffer-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
bearr = { version = "0.1.0", path = "../bearr" }
bearr-executor = { version = "0.1.0", path = "../bearr-executor" }
bytemuck = "1.25.0"
hashbrown = "0.17.0"
io-uring = "0.7.11"
libc = "0.2.185"

[dev-dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
